print('Please enter the following:')
print()
adjective=input('adjective:')
animal=input('animal:')
verb1=input('verb:')
exclamtion=input('exclamation:')
verb2=input('verb:')
verb3=input('verb:')
name=input('name:')
adjective2=input('adjective:')
verb4=input('verb:')
print()
print('Your story is:')
print()
print('The other day, I was really in trouble. It all started when I saw a very')
print( adjective + ' ' + animal + ' ' + verb1 + ' down the hallway. "' + exclamtion+ '" I yelled. But all')
print('I could think to do was to ' + verb2 + ' over and over. Miraculously,')
print('that caused it to stop, but not before it tried to ' + verb3)
print('right in front of my family.')
print('But '+ name + ' saw the whole thing and was so '+ adjective2)
print('we tried to '+ verb4 +' and finially got him back to normal.')